language: php
php:
    - 7.0
    - 5.6
    - 5.5
    - 5.4
    - hhvm

sudo: false

before_script:
    - composer self-update
    - composer install

script:
    - mkdir -p build/logs
    - phpunit

after_script:
    - vendor/bin/coveralls